dist: bionic
language: python
os: linux
addons:
  apt:
    packages:
      - coccinelle
before_script:
    - ccache --version
    - ccache --zero-stats
    - export USE_CCACHE=1
    - conda env create -f environment.yml
    # - git submodule update --init
#     - bash build_dependencies.sh
script:
    - echo $TRAVIS_COMMIT_RANGE
    - CHANGED_FILES=($(git diff --name-only $TRAVIS_COMMIT_RANGE))
    - echo $CHANGED_FILES
    - spatch --version
    - bash patcher.sh $CHANGED_FILES
#     - make build