sudo: required
dist: bionic
language: python
os: linux
# install: test -e .travis-opam.sh || wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh

addons:
  apt:
    packages:
      - opam
before_script:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - source "$HOME/miniconda/etc/profile.d/conda.sh"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - ccache --version
    - ccache --zero-stats
    - export USE_CCACHE=1
    - conda env create -f environment.yml
    - conda activate fixminerEnv
    - opam init --compiler=4.05.0 -y
    - opam update 
    - eval $(opam env)
    - opam install "coccinelle>=1.0.8" -y
    # - git submodule update --init
#     - bash build_dependencies.sh
script:
    # - bash -ex .travis-opam.sh

    - echo $TRAVIS_COMMIT_RANGE
    - CHANGED_FILES=($(git diff --name-only $TRAVIS_COMMIT_RANGE))
    - echo $CHANGED_FILES
    - echo ${GH_TOKEN}
    - echo $GH_TOKEN
    - spatch --version
    - conda activate fixminerEnv
    - bash patcher.sh $CHANGED_FILES
#     - make build
# env:
    # - OCAML_VERSION=4.05 DISTRO=ubuntu
after_success:
    - more /home/travis/build/anilkoyuncu/patcher/patches/inflate.cfor_14_10.cocci.txt