sudo: required
dist: bionic
language: c

os: linux
git:
  clone: false


script:
# - git config --global credential.helper 'cache --timeout=3600'
# - git clone --depth=50 --branch=master https://anilkoyuncu:${GITHUB_TOKEN}@github.com/anilkoyuncu/patcher.git anilkoyuncu/patcher
# - cd anilkoyuncu/patcher
# - bash -ex patcher_dependencies.sh
  - return 1
env:
  matrix:
  - OCAML_VERSION=4.05 DISTRO=ubuntu
  global:
    secure: uCs4p/wmpfUheH1iZs7AhICnli99EqqC3qT5wHBn63xlUTKMYIApEj42326CIZYxfVX1M9nM9y9ZXGlF1becosfnShk27Q/kLPW45WppDI5m4d8r1ysRtvC9sLv0t2i3ntSksuNJRqI9qcKQne8BJI6pLtIK8AbfmD2Xonz0bJYkwRyTrG/Q6NgmRJ79Xt6mNODrTxxvox3NuslQJTaGmdFUzU9MzlLpgHn5ItHfZReVGj847B3qT4NLKFbXC9y1edhEB6wfb7Y8fHxQZudzm4Dob/rGgaynah3w1/yCiCjI3RswtThSzHl/Bc0JbU4S5ByKw87GaYUp5tm6YZjo49ZZxYOksK/uW9WUq5jGow86zItm5mkErSC5GSzPq0zON4ggOXmXawwFShxXjMIRoNilshiSN2E4wR7W5YV7tyVaXnGzq/sijpOc/skeNnXQ124oNeXPia42c10Ffhp1mOeUgr6I/s/5xlf/4WX5uFATDjak6kmOPNGhNnzx++iuqxUzc+5tnQMu7W4WjodTTteaR19m/EAfYWepohmelxuW0fWBXF8qynM6yI/if3AvXJC9AwsDclNZtZHDdAj6tCl/JYzJ+FV7KMZUC/cZ0sgmbSwprhrR0c2GA/T8Q48wem9kWTkbc6T12Ubq65ZJ0IkhVoLuMCU4a9yb6y17N+4=
after_success:
- more /home/travis/build/anilkoyuncu/patcher/patches/inflate.cfor_14_10.cocci.txt
after_failure:
 - echo $TRAVIS_REPO_SLUG
 - git config --global credential.helper 'cache --timeout=3600'
 - cd /home/travis/build/
 - git clone --depth=50 --branch=master https://anilkoyuncu:${GITHUB_TOKEN}@github.com/anilkoyuncu/patcher.git anilkoyuncu/patcher
 - cd anilkoyuncu/patcher
 - pwd
 - echo $TRAVIS_BUILD_DIR
 - bash patcher_dependencies.sh $TRAVIS_COMMIT $TRAVIS_REPO_SLUG