name: fixminerEnv
channels:
  - anaconda
  - defaults
dependencies:
  - numpy
  - pandas
  - pyyaml
  - redis-py
  - scikit-learn
  - networkx=2.1
  - conda-forge::pygithub
  - pip
  - pip:
    # works for regular pip packages
    - git-pull-request
